In [1]:
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

pd.set_option('display.max_columns', 1000)

In [2]:
#df = pd.read_excel('C:/Users/Lenovo PC/Desktop/techlabs/che/from oksana/all_cleaned_num.xlsx')
# df

In [23]:
df = pd.read_excel('https://github.com/TechLabs-Berlin/wt21-pet-match/blob/main/data_set/data_cleaned/all_cleaned_num.xlsx?raw=true')

df

,id,cat_age,cat_gender,breed,needs_outdoor,medical_conditions,behavioural_problems,cat_weight,likes_to_explore,playful,vocal,picked_up,timid,aggressive,adapts_quickly,prefers_alone,likes_stroke,tolerant_handled,friendly,fearful,adopter_gender,adopter_age,other_cats,outdoor_access,worries,easily_nervous,remains_calm,talkative,outgoing,reserved,new_ideas,values_artistic,active_imagination,rude,forgiving,considerate,thorough job,lazy,efficient,satisf_level
0,0,6,1,0,2,2,1,3,4,4,3,2,3,1,3,2,4,3,4,5,2,2,2,2,5,4,4,4,4,4,2,5,3,1,4,5,4,4,4,1.00
1,1,2,2,0,2,1,1,3,4,4,1,4,3,3,2,3,4,3,5,2,2,2,0,2,5,5,5,4,3,5,4,3,4,3,5,5,5,1,5,1.00
2,2,5,1,0,1,1,1,4,5,3,4,2,2,3,4,3,3,2,3,3,2,1,0,1,5,0,0,4,0,2,3,0,4,0,4,0,5,0,0,0.85
3,3,4,2,0,2,1,1,4,3,4,3,5,4,2,2,2,5,4,4,4,2,1,1,2,5,5,2,4,3,4,4,5,5,4,5,4,3,4,3,1.00
4,4,3,2,0,2,1,1,5,4,3,5,2,3,1,4,3,4,3,4,3,2,2,3,2,4,4,4,2,3,4,3,3,3,3,4,4,4,4,4,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,3326,12,2,0,1,1,1,3,5,5,3,4,4,1,4,2,5,4,5,2,2,5,2,1,2,1,4,4,4,2,3,4,3,1,5,5,4,1,4,1.00
3327,3327,7,1,Ragdoll,2,1,1,3,5,4,3,4,3,1,4,1,5,5,4,2,2,4,0,2,2,1,4,3,4,4,5,5,5,2,5,5,4,4,5,1.00
3328,3328,4,1,0,1,1,1,3,5,5,5,5,1,1,5,2,5,5,5,1,2,1,3,1,5,5,3,3,2,4,5,5,5,4,5,5,3,5,4,1.00
3329,3329,1,1,Maine Coon,1,1,1,3,4,5,3,5,4,3,5,1,5,5,5,4,2,3,1,1,4,4,4,1,5,2,3,5,4,4,1,5,5,2,5,1.00
3330,3330,3,1,Cornish Rex,1,1,1,3,4,4,4,5,2,1,4,1,5,5,5,1,2,2,1,1,4,2,3,1,1,5,3,3,3,3,4,3,4,4,4,1.00

In [24]:
df = df.set_index('id').drop(columns = 'breed')

In [25]:
df.head()

,cat_age,cat_gender,needs_outdoor,medical_conditions,behavioural_problems,cat_weight,likes_to_explore,playful,vocal,picked_up,timid,aggressive,adapts_quickly,prefers_alone,likes_stroke,tolerant_handled,friendly,fearful,adopter_gender,adopter_age,other_cats,outdoor_access,worries,easily_nervous,remains_calm,talkative,outgoing,reserved,new_ideas,values_artistic,active_imagination,rude,forgiving,considerate,thorough job,lazy,efficient,satisf_level
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,6,1,2,2,1,3,4,4,3,2,3,1,3,2,4,3,4,5,2,2,2,2,5,4,4,4,4,4,2,5,3,1,4,5,4,4,4,1.00
1,2,2,2,1,1,3,4,4,1,4,3,3,2,3,4,3,5,2,2,2,0,2,5,5,5,4,3,5,4,3,4,3,5,5,5,1,5,1.00
2,5,1,1,1,1,4,5,3,4,2,2,3,4,3,3,2,3,3,2,1,0,1,5,0,0,4,0,2,3,0,4,0,4,0,5,0,0,0.85
3,4,2,2,1,1,4,3,4,3,5,4,2,2,2,5,4,4,4,2,1,1,2,5,5,2,4,3,4,4,5,5,4,5,4,3,4,3,1.00
4,3,2,2,1,1,5,4,3,5,2,3,1,4,3,4,3,4,3,2,2,3,2,4,4,4,2,3,4,3,3,3,3,4,4,4,4,4,1.00

## Random Names feature

In [144]:
# pip install names

import names
#df["cat_gender"] == 1  is 
#df.loc[(df["cat_gender"] == 1 )]

In [118]:

def random_names(name):
    i = 0
    while i < len(df):
        if df["cat_gender"][df.index[i]] == 1:
            i= i+1
            return str(names.get_first_name(gender='male'))
        else:
            i= i+1
            return str(names.get_first_name(gender='female'))

In [119]:

df["cat_name"] = df.apply(random_names,axis=1)
df

,cat_age,cat_gender,needs_outdoor,medical_conditions,behavioural_problems,cat_weight,likes_to_explore,playful,vocal,picked_up,timid,aggressive,adapts_quickly,prefers_alone,likes_stroke,tolerant_handled,friendly,fearful,adopter_gender,adopter_age,other_cats,outdoor_access,worries,easily_nervous,remains_calm,talkative,outgoing,reserved,new_ideas,values_artistic,active_imagination,rude,forgiving,considerate,thorough job,lazy,efficient,satisf_level,cat_name
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,6,1,2,2,1,3,4,4,3,2,3,1,3,2,4,3,4,5,2,2,2,2,5,4,4,4,4,4,2,5,3,1,4,5,4,4,4,1.00,Javier
1,2,2,2,1,1,3,4,4,1,4,3,3,2,3,4,3,5,2,2,2,0,2,5,5,5,4,3,5,4,3,4,3,5,5,5,1,5,1.00,Glenn
2,5,1,1,1,1,4,5,3,4,2,2,3,4,3,3,2,3,3,2,1,0,1,5,0,0,4,0,2,3,0,4,0,4,0,5,0,0,0.85,Earl
3,4,2,2,1,1,4,3,4,3,5,4,2,2,2,5,4,4,4,2,1,1,2,5,5,2,4,3,4,4,5,5,4,5,4,3,4,3,1.00,Willie
4,3,2,2,1,1,5,4,3,5,2,3,1,4,3,4,3,4,3,2,2,3,2,4,4,4,2,3,4,3,3,3,3,4,4,4,4,4,1.00,Ernesto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,12,2,1,1,1,3,5,5,3,4,4,1,4,2,5,4,5,2,2,5,2,1,2,1,4,4,4,2,3,4,3,1,5,5,4,1,4,1.00,Hunter
3327,7,1,2,1,1,3,5,4,3,4,3,1,4,1,5,5,4,2,2,4,0,2,2,1,4,3,4,4,5,5,5,2,5,5,4,4,5,1.00,John
3328,4,1,1,1,1,3,5,5,5,5,1,1,5,2,5,5,5,1,2,1,3,1,5,5,3,3,2,4,5,5,5,4,5,5,3,5,4,1.00,Wesley
3329,1,1,1,1,1,3,4,5,3,5,4,3,5,1,5,5,5,4,2,3,1,1,4,4,4,1,5,2,3,5,4,4,1,5,5,2,5,1.00,Theodore
3330,3,1,1,1,1,3,4,4,4,5,2,1,4,1,5,5,5,1,2,2,1,1,4,2,3,1,1,5,3,3,3,3,4,3,4,4,4,1.00,Robert

In [155]:
### I couldnt fully assingn girl names to female cats 
def random_names_male(name):
    return str(names.get_first_name(gender='male'))

def random_names_female(name):
    return str(names.get_first_name(gender='female'))

df_male = df.loc[(df["cat_gender"] == 1)]
df_male["cat_name"] = df_male.apply(random_names_male,axis=1)

<ipython-input-155-7dfd2e947353>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_male["cat_name"] = df_male.apply(random_names_male,axis=1)

In [156]:

df_female = df.loc[(df["cat_gender"] == 2)]


df_female["cat_name"] = df_female.apply(random_names_female,axis=1)

<ipython-input-156-392f3646d2ab>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_female["cat_name"] = df_female.apply(random_names_female,axis=1)

In [165]:
dfnames = pd.concat([df_male["cat_name"], df_female["cat_name"]], axis = 1 ) 

#dfnames = df_male.append(df_female, sort=False)
#dfnames

,cat_age,cat_gender,needs_outdoor,medical_conditions,behavioural_problems,cat_weight,likes_to_explore,playful,vocal,picked_up,timid,aggressive,adapts_quickly,prefers_alone,likes_stroke,tolerant_handled,friendly,fearful,adopter_gender,adopter_age,other_cats,outdoor_access,worries,easily_nervous,remains_calm,talkative,outgoing,reserved,new_ideas,values_artistic,active_imagination,rude,forgiving,considerate,thorough job,lazy,efficient,satisf_level,cat_name
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,6,1,2,2,1,3,4,4,3,2,3,1,3,2,4,3,4,5,2,2,2,2,5,4,4,4,4,4,2,5,3,1,4,5,4,4,4,1.00,Raul
2,5,1,1,1,1,4,5,3,4,2,2,3,4,3,3,2,3,3,2,1,0,1,5,0,0,4,0,2,3,0,4,0,4,0,5,0,0,0.85,Robert
6,3,1,2,1,2,3,4,4,3,4,2,1,3,2,4,5,4,1,2,2,1,2,3,2,4,4,3,4,5,4,5,2,4,4,5,4,3,0.90,Jason
7,8,1,1,1,1,3,4,4,4,5,2,1,4,1,4,4,5,2,2,3,0,1,3,3,3,3,2,3,4,2,2,2,3,4,5,2,5,1.00,Ronald
8,10,1,1,2,1,3,4,4,5,5,2,1,4,4,5,5,5,3,2,2,0,1,4,3,4,4,4,3,5,4,4,2,5,5,4,3,5,1.00,Larry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3318,14,2,1,2,1,3,3,2,3,4,4,1,2,3,4,3,4,1,2,5,0,1,4,3,5,1,3,4,3,4,3,1,3,3,5,3,5,0.70,Helene
3322,15,2,1,1,1,3,5,4,5,4,1,1,5,1,5,5,5,1,2,5,9,1,2,1,4,4,4,2,5,4,4,2,4,5,5,2,5,1.00,Charlotte
3323,2,2,2,1,1,3,5,5,4,4,2,1,4,1,4,4,4,2,2,4,11,2,2,2,5,3,2,4,4,3,4,2,2,4,5,1,5,0.95,Karen
3325,1,2,1,1,1,3,3,4,3,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,Jessica
3326,12,2,1,1,1,3,5,5,3,4,4,1,4,2,5,4,5,2,2,5,2,1,2,1,4,4,4,2,3,4,3,1,5,5,4,1,4,1.00,Sandra

## regression Test

In [ ]:

X = df.iloc[:, :37]
y = df.iloc[:, 37]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=80)

In [7]:
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
# we must apply the scaling to the test set that we computed for the training set
X_test_scaled = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [ ]:
LR = LinearRegression()
linreg=LR.fit(X_train,y_train)

Simple evaluation

In [ ]:
y_pred =  LR.predict(X_test)
print('Accuracy on training set: {:.2f}'.format(LR.score(X_train, y_train)))
print('Accuracy on test set: {:.2f}'.format(LR.score(X_test, y_test)))

In [ ]:
print('linear model coeff (w): {}'
     .format(linreg.coef_))
print('linear model intercept (b): {:.3f}'
     .format(linreg.intercept_))
print('R-squared score (training): {:.3f}'
     .format(linreg.score(X_train, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linreg.score(X_test, y_test)))

In [ ]:
compare = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
compare

In [ ]:
## testing 

#example_person = [[5.5, 2.2, 10, 0.70]]
#example_satisfied_scaled = scaler.transform(example_person)
#print('Predicted fruit type for ', example_fruit, ' is ',LR.predict(example_satisfied_scaled))

# Satisfaction levels lower than 100%

In [ ]:
# Note the accurancy is much higher in satisfaction less than 100%
lower_100 = df.loc[df["satisf_level"]!=1].fillna(0)
X = lower_100.iloc[:, :37]
y = lower_100.iloc[:, 37]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=80)
LR_lower_100 = LinearRegression()
LR_lower_100.fit(X_train,y_train)
print('Accuracy on training set: {:.2f}'
     .format(LR_lower_100.score(X_train, y_train)))
print('Accuracy on test set: {:.2f}'
     .format(LR_lower_100.score(X_test, y_test)))

## Run the test

In [ ]:
#df = pd.read_csv('https://github.com/TechLabs-Berlin/wt21-pet-match/blob/main/data_set/data_cleaned/all_cleaned_num.xlsx?raw=true')

#### L.regression predict person saisfaction no based on ist features

In [ ]:
X_adopt = df.iloc[:, 20:-1]
y_satisf_adopt = df.iloc[:, 37]
X_train, X_test, y_train, y_test = train_test_split(X_adopt, y_satisf_adopt, test_size=0.25, random_state=43)

In [ ]:
LR = LinearRegression()
linreg=LR.fit(X_train,y_train)

In [ ]:
y_adopt =  LR.predict(X_test)
print('Accuracy on training set: {:.2f}'.format(LR.score(X_train, y_train)))
print('Accuracy on test set: {:.2f}'.format(LR.score(X_test, y_test)))

#### L.regression predicting Cat satisfaction no based on its features

In [ ]:
X_cat = df.iloc[:, :20]
y_satisf_cat = df.iloc[:, 37]
X_train, X_test, y_train, y_test = train_test_split(X_adopt, y_satisf_cat, test_size=0.25, random_state=80)
LR = LinearRegression()
linreg=LR.fit(X_train,y_train)

In [ ]:
y_cat =  LR.predict(X_test)
print('Accuracy on training set: {:.2f}'.format(LR.score(X_train, y_train)))
print('Accuracy on test set: {:.2f}'.format(LR.score(X_test, y_test)))

#### Testing the Effect

In [ ]:
compare = pd.DataFrame({'Actual': y_test, 'Predicted_adopt': y_adopt, 'Predicted_cat': y_cat})
compare

### Recommender system (reccomends best matching cat, after you get we get the adopter  staisfcation )

In [ ]:
### What is the important features 

#lets try cooilartion matrix 
df_matrix = df.corr()
sn.heatmap(df_matrix ,annot= True, ax=plt.axes(), cmap="YlGnBu").set_title("Correlation between adopter personality and cat qualities")
plt.gcf().set_size_inches(40, 25)

In [ ]:
#adoter gender and stisfaction ???

# main features are (picked_up,adapts_quickly,likes_stroke,friendly)

## maybe Adopters scores need to clusted accoding to BFi

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
features = ['picked_up', 'adapts_quickly', 'likes_stroke', 'friendly']

## note: this Dataset only works on 25% (i need to find a way to make work on the whole one)

In [ ]:
### for convinance i took the 25% of the sample test for pridection 

dfRecommend = pd.concat([compare, df[['picked_up','adapts_quickly','likes_stroke','friendly']]], axis = 1).reindex(compare.index)

#dfRecommend.isna().value_counts()

dfRecommend["cat_index"]= dfRecommend.index
dfRecommend

In [ ]:

def combine_features(row):
    return str(row['Predicted_cat'])+" "+str(row['picked_up'])+" "+str(row['adapts_quickly'])+" "+str(row['likes_stroke'])+" "+str(row['friendly'])

In [ ]:
for feature in features:
    dfRecommend[feature] = dfRecommend[feature].fillna('') #filling all NaNs with blank string
    


dfRecommend["combined_features"] = dfRecommend.apply(combine_features,axis=1) #applying combined_features() method over each rows of dataframe and storing the combined string in "combined_features" column
dfRecommend

In [ ]:
cv = CountVectorizer() #creating new CountVectorizer() object
count_matrix = cv.fit_transform(dfRecommend["combined_features"])

In [ ]:
#  the cosine similarity matrix from the count matrix.
cosine_sim = cosine_similarity(count_matrix)

In [ ]:
def get_satisfaction_from_catIndex(cat_index):
    return dfRecommend[dfRecommend.cat_index == cat_index]["Predicted-adopt"].values[0]


def get_catIndex_from_satisfaction(Predicted_adopt):
    return dfRecommend[dfRecommend.Predicted_adopt == Predicted_adopt]["cat_index"].values[0]

In [ ]:
get_catIndex_from_satisfaction(0.9396129885133185)

In [ ]:
dfRecommend["Predicted_adopt"][dfRecommend.index[5]]

In [ ]:
expeted_adopter_likes = dfRecommend["Predicted_adopt"][dfRecommend.index[20]]
cat_id = get_catIndex_from_satisfaction(expeted_adopter_likes)
similar_cats = list(enumerate(cosine_sim[cat_id]))

In [ ]:
sorted_similar_cats = sorted(similar_cats,key=lambda x:x[1],reverse=True)[1:]


best_matches =sorted_similar_cats[0:1000]
best_matches